# -*- coding: utf-8 -*-
"""날짜시간함수 연습.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10Av9KSKqVKGdMrk_sQeqEajQtQfuzwJw
"""

from datetime import datetime, date, time, timedelta

now = datetime.now()  # 현재날짜 시간
print(now)
print(now.year)    # 년
print(now.month)   # 월
print(now.day)     # 일
print(now.hour)    # 시
print(now.minute)  # 분
print(now.second)  # 초

d = date(2025, 12, 30)  # date() 생성자를 통해 날짜 객체 생성
print(d)

t = time(14, 30, 12)
print(t)

dt = datetime(2025, 12, 30, 9, 0, 0)
print(dt)

dt = datetime.strptime("2025-03-15 10:03:00", "%Y-%m-%d %H:%M:%S")  # 문자열을 -> 날짜 시간 객체로 변환
print(dt)

print(dt.strftime("%Y/%m/%d 시간 %H:%M:%S"))  # 날짜시간객체들 -> 문자열로 변환

today = date.today()
print(today + timedelta(days=7))
print(today - timedelta(days=30))

now = datetime.now()
print(now + timedelta(hours=10)) # 10시간 후
print(now + timedelta(minutes=30)) # 30분 후

d1 = date.today()
d2 = date(2003, 1, 17)
print((d1 - d2).days // 365)

yoil = ["월", "화", "수", "목", "금", "토", "일"]

print(d1.weekday(), yoil[d1.weekday()])   # 월[0]~
print(d1.isoweekday(), yoil[d1.isoweekday() - 1])

print(d1.strftime("%Y년 %m월 %d일 %a"))

import time

print(time.time())

time.sleep(5)
print("5초후 출력")

start = time.time()
for i in range(10000000):
  pass
end = time.time()
print(end - start)

import calendar

print(calendar.month(2025,12))

from datetime import datetime
from zoneinfo import ZoneInfo

utc = datetime.now(tz=ZoneInfo("UTC"))
print(utc)

seoul = datetime.now(tz=ZoneInfo("Asia/Seoul"))
print(seoul)

d1 = date(2025, 3, 1)
d2 = date(2025, 3, 10)

print(d1 < d2)    # True
print(d1 == d2)    # False

